name: Deploy to EC2

on:
  push:
    branches: [ "main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.6.0

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build the app
        run: |
          cd client
          npm run build
